version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
      - ./cert:/cert
      - /app/node_modules
    # links:
    #   - server:api-server
    command: yarn serve
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "1"

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 3333:3333
    volumes:
      - ./server:/app
      - ./cert:/cert
      - /app/node_modules
    links:
      - mysql:mysql
      - app:app
    command: npm run dev
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "1"

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      # MYSQL_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: adonis
      MYSQL_USER: adonis
      MYSQL_PASSWORD: adonis
      MYSQL_TEST_DATABASE: adonis-test
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    # expose:
    #   - 3306
    ports:
      - 0.0.0.0:3316:3306
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "1"
